oracle-cne/ocne

buildrpm/ocne.spec
cmd/cluster/console/console.go
pkg/commands/cluster/console/console.go
test/bats/console/console.bats

Adds the ability to specify commands to run in the cluster console using "--", as with kubectl and other CLIs.
```
1..4
ok 1 Console can execute commands on a node
ok 2 Console can execute commands on a node using --direct
ok 3 Console without --direct runs in the container
ok 4 Console with --direct runs in the host
```

Add support for double dash command passing in cluster console

---

cmd/application/update/update.go
doc/manpages/ocne-application.md
pkg/commands/application/types.go
pkg/commands/application/update/update.go

Added option to ```ocne application update``` to specify which catalog to use.
Test case to verify change worked:
```
ocne cluster start -u false
ocne catalog add --uri https://oracle.github.io/weblogic-kubernetes-operator --name "WebLogic Kubernetes Operator"
ocne application install -c "WebLogic Kubernetes Operator" --release weblogic-operator --namespace weblogic-operator --name weblogic-operator --version 4.2.3
ocne application update --release weblogic-operator --namespace weblogic-operator --version 4.2.7 --catalog "WebLogic Kubernetes Operator"
```
I also verified the application tests passed:
```
make integration-test TEST_PATTERN=default TEST_FILTERS="--filter-tags APPLICATION"
```

Add catalog option to ocne application update (2)

---

cmd/application/update/update.go
doc/manpages/ocne-application.md
pkg/commands/application/install/install.go
pkg/commands/application/types.go
pkg/commands/application/update/update.go
pkg/helm/helmcli.go
test/bats/application/update.bats

Added a ```--reset-values``` option to ```ocne application update``` as per the description in the linked task.  This new option is analogous to the underlying helm option with the same name.
Added a new bats test to verify this change.

Add option to "ocne app update" to reset the overrides to the ones built into the chart

---

cmd/cluster/dump/dump.go
pkg/commands/cluster/dump/capture/capture.go
pkg/commands/cluster/dump/capture/clusterinfo.go
pkg/commands/cluster/dump/capture/k8sresource.go
pkg/commands/cluster/dump/capture/pod.go
pkg/commands/cluster/dump/capture/sanitize/sanitize.go
pkg/commands/cluster/dump/capture/sanitize/sanitize_test.go
pkg/commands/cluster/dump/cluster.go
pkg/commands/cluster/dump/node.go
pkg/commands/cluster/info/info.go

In this PR, I refactored some of the sanitization code in order to fix the case where the cluster-info.out file was not displaying its full output when a redacted cluster dump was being used to generate it. 
Output of cluster-info.out file when a redacted dump is ran 
```
Cluster Summary:
control plane nodes: 1
worker nodes: 0
nodes with available updates: 0
Nodes:
Name                  Role            State   Version         Update Available
----                  ----            -----   -------         ----------------
REDACTED-dd54744c     control plane   Ready   v1.29.3+3.el8   false
Node: REDACTED-dd54744c
Registry and tag for ostree patch images:
registry: sample-registry
tag: 1.29
transport: ostree-unverified-registry
Ostree deployments:
...
```
Output of cluster-info.out file when …

Fix case where cluster-info.out file was not displaying full output when a redacted dump was used

---

cmd/image/create/create.go
pkg/cluster/ignition/library.go
pkg/cmdutil/config.go
pkg/commands/image/create/ostree.go
pkg/image/registry.go
pkg/image/registry_test.go
test/bats/image/image.bats
test/run-tests.sh

Changes how ostree image parsing works to handle more cases and split the image URI into more useful chunks.  The places where ostree images are consumed, especially when mixed with the syntax required for skopeo, have been updated to take advantage of this.

Allow custom ostree transports for update configuration

---

README.md

The ocne repo README.md file is missing a link to the Oracle OCNE 2.0 documentation. Also, the quick start steps in the README.md do not work unless you set up prerequisites. Do the following:
1. Add link to the Oracle OCNE 2.0 documentation
2. Add a link to the libvirt quickstart in that documentation.  This has all the prerequisite steps for run the CLI.
3. Remove the setup commands
NOTE: You can select "view file" in the .. menu when viewing README.md.  You  will see the doc links then click on them.

Add doc links to the README.md

---

cmd/cluster/delete/delete.go

As part of https://github.com/oracle-cne/ocne/pull/8 there was a change in the order of evaluation for some cluster configuration options.  The necessary adaptations to cluster delete were not made, and as a result cluster delete would always use the libvirt provider.
Here's a demonstration that this new code works:
```
[opc@dkrasins-dev-ol9 ocne]$ ./out/linux_amd64/ocne cluster delete -c capi.yaml
INFO[2024-09-30T19:14:06Z] Deleting file /home/opc/.kube/kubeconfig.ocne.local 
INFO[2024-09-30T19:14:06Z] Deleting file /home/opc/.kube/kubeconfig.ocne.vm 
INFO[2024-09-30T19:18:59Z] Installing cert-manager into cert-manager: ok 
INFO[2024-09-30T19:19:01Z] Installing core-capi into capi-system: ok 
INFO[2024-09-30T19:19:04Z] Installing capoci into cluster-api-provider-oci-system: ok …
```

Fix regression were provider was possible ignored in cluster delete

---

cmd/cluster/template/template.go
doc/manpages/ocne-config.yaml.md
pkg/cluster/template/capi-oci.go

Example cluster configuration file: capi.yaml
```shell
provider: oci
name: pras-cluster
workerNodes: 3
controlPlaneNodes: 3
clusterDefinition: mycluster.oci
.....
.....
```
Create a new ClusterAPI yaml using
```shell
ocne cluster template -c capi.yaml > mycluster.oci
```
Cluster name correctly set to "pras-cluster" instead of "ocne". Other references to "ocne" that correctly updated as well.
```shell
$ grep --context=10 clusterName mycluster.oci
cloud-provider: external
provider-id: oci://{{ ds["id"] }}
volume-plugin-dir: "/var/lib/kubelet/volumeplugins"
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
name: "pras-cluster-md-0"
namespace: "pras-ns"
spec:
clusterName: "pras-cluster"
replicas: 3
selector:
matchLabels:
template:
spec:
clusterName: "pras-cluster" …
```

Set cluster name and number of control plane nodes from cluster configuration file for the "ocne cluster template" command.

---

doc/experimental/oam-to-kubernetes.md

Add VZ 1.6.11 CLI download instructions since it is needed to generate Kubernetes YAML manifests from cluster resources related to OAM.

Add VZ 1.6.11 CLI download instructions

---

pkg/cluster/driver/capi/capi.go

Adds some easy startup checks to ensure that a minimum amount of information is provided when starting an OCI CAPI cluster.

Validate that OCI-CCM configuration is set before starting an OCI cluster

---

pkg/cluster/template/capi-oci.go
pkg/constants/constants.go

add oci-instance-metadata-endpoint to noproxy to fix ocid-populate.conf and kubeadm.yml

add oci-instance-metadata-endpoint to noproxy

---

doc/experimental/disable-verrazzano.md
doc/experimental/phase1.md

Update the experimental docs to include instructions of how to upgrade from Istio 1.19.0 to 1.19.9.

Add instructions for migrating from istio 1.19.0 to 1.19.9

---

pkg/cluster/ignition/virtual_ip.go

Bump the `kubectl get node` to 1 minute.  Please see the linked issue for details

Increase keepalived liveness timeout to 1m to account for resource contention under load

---

doc/experimental/phase1.md

Update the experimental docs to describe how to migrate to the Fluentd in the app-catalog.

Document how to migrate verrazzano fluentd

---

doc/experimental/phase1.md

Add instructions to the experimental documents on how to migrate  the Verrazzano install of cert-manager to app-catalog.

Add instructions to migrate cert-manager

---

doc/experimental/phase1.md

Add instructions to the experimental docs for upgrade the Verrazzano 1.3.1 install of prometheus-node-export to the 1.6.1 version in the app-catalog.
Fixed a bug in the cert-manager migration instructions.

Add instructions to upgrade prometheus-node-exporter

---

doc/experimental/phase1/copy-prom-data-alternate.md
doc/experimental/phase1/copy-pv-different-ad.md
doc/experimental/phase1/kube-prometheus-stack.md

If a pod cannot mount both old and new PVs at once, then we need to use 2 pods can copy the data to and from the local system.

Migrate Prometheus data via local system

---

pkg/config/config.go
pkg/constants/constants.go

Allows users to override the location of the default configuration file.
Example
```
#
#
$ cat ~/.ocne/defaults-noproxy.yaml
extraIgnitionInline: |
variant: fcos
version: 1.5.0
passwd:
users:
- name: dkrasins
groups:
- wheel
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDAfNhm5APW2kctfj+O8IRInlFivqoQMvMQ9CCNMq5IavW+CKTJUQ74pn8YkAmagM44zXPpwDoFiE+Wmk7fncigMu/x6T1qDLlz0P5XCXU1LQD35MOjtzQPyIRngaDbJ3f4H34w/WzyFVAH4wOPCiTa3eHRWU9ZLBK5MooDp1paC91NDUU4iLmRIVgBPbI7XPziRRvKQpUo9MPmXSjvOY/bvwAFZZB0uePR6RQBofVABisUJEE1Coo3EZmreekoreftUH6Xm+JI016sXMkQydfHsHztEL2C4zYUOfZmya0ThWkYSelUyZmOJU+3R3CQ56F04YGdqIQPA7WLGH0Q/IXzIGE2cNVxsceFraVLCuRTnzHoh4Hg6BrfVWWAm2siGNZP/6hldA3TIpyHMDKE6wJ3T/iONP1eI6ojgz6rnRUQzgxzjEGCpSuoFWaPlweYKksldIuflKijC3jGAbmqFNe/6UMVmGk7nRu/IE2K7XO/bgSTOCxf+KPUBCfATGiK3y0= …
```

Added OCNE_DEFAULTS environment variable to change the path of the default configuration

---

cmd/cluster/delete/delete.go
cmd/cluster/start/start.go
cmd/cluster/template/template.go
pkg/cluster/driver/none/none.go
pkg/cluster/template/templates.go
pkg/commands/application/install/applications.go
pkg/commands/cluster/start/start.go
pkg/constants/constants.go

When starting a cluster with the "none" provider, override the registry value for the app-catalog and ui if it is set in defaults.yaml (and different than the setting in values.yaml)
Created constants for the provider types.

Honor the registry override in defaults.yaml for the "none" provider

---

doc/experimental/phase1/kube-prometheus-stack.md

Fix ServiceMonitors and PodMonitors to bind to new Prometheus Operator.  This is done by changing the release label.  Without this fix, the operator will not process the monitor resources.
With this fix, all the scrape targets are working for both envoy metrics and app metrics.
Also remove edit to Kiali authorizationpolicy, which is not needed.

Fix ServiceMonitors and PodMonitors to bind to new Prometheus Operator

---

pkg/config/config.go

I tested that the erroneous file is identified in the output in the case that 
1. the default file is invalid
2. the user passed in file is invalid
3. both are invalid
I also tested the case where both files are valid and made sure no error is observed.

 131-yaml-parse-errors-are-not-attributed-to-the-bad-file 

---

cmd/image/create/create.go
pkg/commands/image/create/create.go
pkg/commands/image/create/scripts.go

Allows users to specify custom ignition providers and extra kernel arguments.
Examples:
```
[opc@dkrasins-dev-ol9 ocne]$ ./out/linux_amd64/ocne image create -i 'mycoolprovider' -K 'my cool args'
INFO[2024-10-30T17:52:24Z] Creating Image                               
INFO[2024-10-30T17:52:24Z] Preparing pod used to create image           
INFO[2024-10-30T17:52:29Z] Waiting for pod ocne-system/ocne-image-builder to be ready: ok 
INFO[2024-10-30T17:52:29Z] Getting local boot image for architecture: amd64 
INFO[2024-10-30T17:52:50Z] Uploading boot image to pod ocne-system/ocne-image-builder: ok 
INFO[2024-10-30T17:53:45Z] Downloading boot image from pod ocne-system/ocne-image-builder: ok 
INFO[2024-10-30T17:53:45Z] New boot image was created successfully at …
```

Allow arbitrary ignition provider configuration and extra kernel arguments

---

Makefile
buildrpm/ocne.spec
cmd/info/info.go
doc/manpages/ocne-info.md

First pass of adding version and commit information to the CLI 
Example Output: 
```
./ocne info
CLI Info
Name     	Value                                   
Version  	2.0.4-3.el8                             
BuildDate	2024-11-05T09:43:59Z                    
GitCommit	55d88909e7629339d2428adc1a3bc92af22669dd
Environment Variables
Name         	Description                                       	Current Value
OCNE_DEFAULTS	Sets the location of the default configuration    	             
file.                                             	             
KUBECONFIG   	Sets the location of the kubeconfig file. This    	             
behaves the same way as the --kubeconfig option   	             
for most ocne commands.                           	             
EDITOR       	Sets the default …
```

140 add version and commit information to ocne cli and fix run directive

---

pkg/commands/cluster/info/info.go

In this PR, I fix the issue where nodes were not being skipped during the output of the `ocne cluster info` command. 
```
./ocne cluster info -s
Cluster Summary:
control plane nodes: 1
worker nodes: 0
nodes with available updates: 0
Nodes:
Name                  Role            State   Version         Update Available
----                  ----            -----   -------         ----------------
ocne-test-node  control plane   Ready   v1.30.3+1.el8   false
```
```
./ocne cluster info   
INFO[2024-11-05T11:28:47-05:00] Collecting node data                         
Cluster Summary:
control plane nodes: 1
worker nodes: 0
nodes with available updates: 0
Nodes:
Name                  Role            State   Version         Update Available
----                  ----            -----   ------- …
```

Fix nodes not being skipped during cluster info

---

pkg/commands/cluster/dump/capture/clusterinfo.go
pkg/commands/cluster/dump/dump.go

In this PR, I fix the `cluster dump` command to have the correct output when nodes are skipped 
```
cat cluster-info.out 
Cluster Summary:
control plane nodes: 1
worker nodes: 0
nodes with available updates: 0
Nodes:
Name                  Role            State   Version         Update Available
----                  ----            -----   -------         ----------------
REDACTED-dd54744c     control plane   Ready   v1.30.3+1.el8   false
```

Fix cluster dump to have the correct cluster-info.out file, when nodes are skipped

---

pkg/commands/cluster/dump/capture/clusterinfo.go
pkg/commands/cluster/dump/dump.go
pkg/commands/cluster/dump/node.go
pkg/commands/cluster/info/info.go

In this PR, I fixed bugs that occurred when the `cluster dump `and` cluster info` commands were not validating nodes and outputting incorrect information when an incorrect node list was given. I also fixed a bug that occurred when incorrect information was displayed when a partial, but valid node list was given. 
Example Where Error Is Thrown After Non-Existent Node is specified:
```
./ocne cluster info -N actual-node, non-existent-node                     
ERRO[2024-11-06T10:24:59-05:00] The following node resources do not exist: [non-existent-node] 
```
Example where the output is presented correctly after a partial list of nodes is specified:
```
./ocne cluster info -N ocne-worker-node
INFO[2024-11-06T10:34:29-05:00] Collecting node data                         
Cluster Summary: …
```

Fix Other Bugs in Cluster Dump and Cluster Info Regarding Nodes

---

Makefile

Introduced environment variable CATALOG_BRANCH  to customize catalog branch when building ocne cli. Example:
```shell
CATALOG_BRANCH="27-istio-1.21" make clean cli
```
Fixed typo in dependency of make target `build-cli-instrumented`. Otherwise below command would fail.
```shell
$ make clean build-cli-instrumented 
rm -rf pkg/catalog/embedded/charts
rm -rf build/charts
rm -rf build
rm -rf out
mkdir -p out/linux_amd64_instrumented
GO111MODULE=on GOPRIVATE=github.com/oracle-cne/ocne go build -cover -trimpath -ldflags "-X 'github.com/home/opc/projects/work/oracle-cne/ocne/cmd/info.gitCommit=20d48f48c6eeb727aaba5a73e4026e8d5761991f' -X 'github.com/home/opc/projects/work/oracle-cne/ocne/cmd/info.buildDate=2024-11-09T01:45:05Z' -X 'github.com/home/opc/projects/work/oracle-cne/ocne/cmd/info.cliVer …
```

Introduced environment variable CATALOG_BRANCH  to customize catalog branch. Fixed typo in dependency of target build-cli-instrumented.

---

pkg/helm/helmcli.go

"ocne application update" command failing when install did not customize any helm values initially.
Fixed map variable from becoming nil
```shell
$ ocne application update --release istiod --version 1.19.9 --catalog embedded --namespace istio-system --values - << EOF
> ownerName: helm
> EOF
INFO[2024-11-14T23:26:05Z] Updating release istiod                      
INFO[2024-11-14T23:26:05Z] Application updated successfully
$ ocne  application show --release istiod --namespace istio-system
ownerName: helm
----------------
NAME: istiod
NAMESPACE: istio-system
CHART: istiod
STATUS: deployed
REVISION: 3
APPVERSION: 1.19.9
```

"ocne application update" command failing when install did not customize any helm values initially

---

cmd/cluster/analyze/analyze.go
cmd/cluster/dump/dump.go
doc/manpages/ocne-cluster.md
pkg/commands/cluster/analyze/analyze.go
pkg/commands/cluster/analyze/dumpfiles/jsonfile.go
pkg/commands/cluster/analyze/event.go
pkg/commands/cluster/analyze/node.go
pkg/commands/cluster/analyze/pod.go
pkg/commands/cluster/analyze/types.go
pkg/commands/cluster/dump/capture/capture.go
pkg/commands/cluster/dump/capture/k8sresource.go
pkg/commands/cluster/dump/cluster.go
pkg/commands/cluster/dump/dump.go

In this PR, I add support for YAML in the `cluster dump` and `analyze`, making it the default behavior, unless the -j is specified. With cluster `info`, a YAML dump is always used, it is also used when analyzing a live cluster. A bug was also fixed, where the `cluster analyze` command would not error if an incorrect path was given. The managed fields portion of Kubernetes resources was also removed by default. 
Example of output of the namespace resource list in default/YAML format with no managed Fields
```
./ocne cluster dump  -d  test-yaml-dump
INFO[2024-11-12T16:49:47-05:00] Collecting node data                         
INFO[2024-11-12T16:49:47-05:00] Collecting cluster data                      
INFO[2024-11-12T16:49:57-05:00] Cluster dump successfully completed 
cat …
```

Add YAML output  in cluster dump and analyze and remove managed fields by default 

---

cmd/application/application.go
cmd/catalog/catalog.go
cmd/cluster/cluster.go
cmd/common/common.go
cmd/image/image.go
cmd/node/node.go

See associated task for description.
Example of output with these changes:
```
$ ocne app
Manage ocne applications
Usage:
ocne application [flags]
ocne application [command]
Examples:
ocne application install
Available Commands:
install     Install an application from an application catalog or install the built-in catalog
list        List installed applications
show        Show application details
template    Generate an application configuration template
uninstall   Uninstall an application.
update      Update an application from an application catalog or update the built-in catalog
Flags:
-h, --help                help for application
-k, --kubeconfig string   the kubeconfig filepath
Global Flags:
-l, --log-level string   Sets the log level.  Valid values are "error", "info", "debug", …
```

Have ocne automatically show help in some use cases

---

pkg/cluster/driver/libvirt/libvirt.go
pkg/k8s/client/config.go

Sample output:
```
$ ocne cluster start -u false
ERRO[2024-12-19T17:12:30-05:00] Failed to start cluster "ocne". The libvirt domain "ocne-control-plane-1" is running. 
ERRO[2024-12-19T17:12:30-05:00] stat /Users/mgianata/.kube/kubeconfig.ocne.local: no such file or directory 
```

Improve error information when cluster fails to start for libvirt provider

---

pkg/cluster/template/olvm/ignition.go
pkg/commands/image/create/create.go
pkg/commands/image/create/oci.go
pkg/commands/image/create/olvm.go
pkg/commands/image/create/olvm_scripts.go

This PR implements olvm image create --type olvm. 
changes:
1. add create olvm image logic in go
2. add create olvm script (derived from oci script)
3. moved create oci code to its own go file
4. updated olvm ignition code to fix service issues
The script is a subset of the --type oci script, where the kernel args have the ignition type is set to openstack, and the console=tty0
Also, when testing with the latest OCK images there were some issues related to services being disabled and starting too soon.  I had to disable several services, then re-enable some right before kubeadm service runs.  You can see that in the ignition.go code.  If I didn't disable these services temporarily, there was some sort of startup race condition where it took a very long time (maybe 10 min) for the first …

implement olvm image create --type olvm

---

doc/cluster-management/olvm.md

This is the initial pass at OLVM documentation.  This document explains how to create a Kubernetes cluster on an OLVM instance.  This is initially for a developer release.

Initial pass at OLVM doc

---

doc/manpages/ocne-catalog.md

Added explanation of the copy command and checked the catalog copy code for any important information that may need to be documented.
Note: The catalog copy command currently only supports docker references and may not work with other types of destinations.

Added manpage explanation for the catalog copy command

---

pkg/commands/cluster/stage/stage.go

This was happening during cluster stage with a KUBECONFIG because I'm a big old dummy and did an incorrect client lookup:
```
[opc@ol9 ocne]$ ./out/linux_amd64/ocne cluster stage --version 1.27 --log-level debug
DEBU[2025-01-15T20:15:10Z] Have cluster config <nil>                    
W0115 20:15:10.715746 3325031 client_config.go:659] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0115 20:15:10.715761 3325031 client_config.go:664] error creating inClusterConfig, falling back to default config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
ERRO[2025-01-15T20:15:10Z] invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable …
```

Fix regression when staging cluster with KUBECONFIG

---

doc/experimental/phase1/phase1.md
doc/experimental/phase1/update-opensearch.md
doc/experimental/phase1/upgrade-opensearch.md
doc/experimental/phase3/phase3.md

Add instructions to demonstrate how to upgrade the Verrazzano install of OpenSearch 2.3.0 to 2.15.0 and be managed by a helm chart in the once-catalog.

Add experimental instructions for upgrading OpenSearch 2.3.0 to 2.15.0

---

doc/experimental/phase1/phase1.md

Update the phase1 doc to delete the VMI with no cascade.  This must be done before deleting the VMO CRD or else the VMI owned resources will be deleted when the VMI is deleted.

Update migration phase1 doc to delete the vmi resource

---

pkg/catalog/versions/k8s.go
pkg/cluster/ignition/kubeadm.go
pkg/constants/constants.go

Adds support for Kubernetes 1.31
Flannel Test
```
[opc@ol9 ocne]$ ./out/linux_amd64/ocne cluster start --control-plane-nodes 3 --worker-nodes 3
INFO[2025-02-06T01:48:43Z] Creating new Kubernetes cluster with version 1.31 named ocne 
INFO[2025-02-06T01:49:37Z] Waiting for the Kubernetes cluster to be ready: ok 
INFO[2025-02-06T01:49:42Z] Installing core-dns into kube-system: ok 
INFO[2025-02-06T01:49:43Z] Installing kube-proxy into kube-system: ok 
INFO[2025-02-06T01:49:44Z] Installing flannel into kube-flannel: ok 
INFO[2025-02-06T01:49:46Z] Installing ui into ocne-system: ok 
INFO[2025-02-06T01:49:47Z] Installing ocne-catalog into ocne-system: ok 
INFO[2025-02-06T01:49:47Z] Kubernetes cluster was created successfully  
INFO[2025-02-06T01:51:17Z] Waiting for the UI to be ready: ok 
Run …
```

Add kubernetes 1.31

---

pkg/cluster/ignition/ignition.go

It can be hard to figure out why extra ignition is giving unexpected results.  Treat warnings as errors both to log the issue as well as to force end users to keep their ignition/butane configuration clean.
```
[opc@ol9 ocne]$ ./out/linux_amd64/ocne cluster start -c <( cat << EOF
> extraIgnitionInline: |
>   variant: fcos
>   version: 1.5.0
>   fakeKey: fakeVal
> EOF
> )
INFO[2025-02-26T15:11:57Z] Creating new Kubernetes cluster with version 1.31 named ocne 
ERRO[2025-02-26T15:11:57Z] could not parse extra ignition: warning at $.fakeKey, line 3 col 1: Unused key fakeKey 
$ ./out/linux_amd64/ocne cluster start -c <(cat << EOF
> extraIgnitionInline: |
>   variant: fcos
version: 1.5.0
passwd:
users:
- name: dkrasins
password_hash: "<omitted>"
groups:
- wheel
> EOF
> ) …
```

Treat ignition/butane warnings as errors

---

cmd/image/upload/upload.go
doc/manpages/ocne-config.yaml.md
doc/manpages/ocne-defaults.yaml.md
doc/manpages/ocne-image.md
pkg/cluster/driver/capi/capi.go
pkg/cluster/driver/capi/stage.go
pkg/cluster/template/oci/capi-oci.go
pkg/commands/image/upload/types.go
pkg/commands/image/upload/upload.go
pkg/config/config.go
pkg/config/types/types.go
pkg/constants/constants.go
pkg/util/oci/compartment.go
pkg/util/oci/config.go
pkg/util/oci/image.go
pkg/util/oci/objectstorage.go
pkg/util/oci/workrequests.go

A user may have an OCI configuration file with multiple profiles.  Switching between them today requires changing the profile to use to "DEFAULT".  This is annoying.  A profile can now be passed into all OCI API connections.
```
$ cat ~/.oci/config
[PROFILEONE]
...
[PROFILETWO]
...
[DEV]
...
$ ./out/linux_amd64/ocne image upload --compartment sandboxes/daniel.krasinski --bucket images --file /home/opc/.ocne/images/boot.qcow2-1.31-amd64.oci --arch amd64 --version 1.31 --profile DEV
INFO[2025-02-26T17:08:45Z] Uploading image to object storage: ok 
INFO[2025-02-26T17:22:45Z] Importing compute image: [##########]: ok 
INFO[2025-02-26T17:22:45Z] Image OCID is ocid1.image.oc1....
$ cat ~/.oci/config
[PROFILEONE]
...
[PROFILETWO]
...
[DEFAULT]
...
$ ./out/linux_amd64/ocne image upload …
```

Allow custom OCI config profile

---

pkg/image/registry.go
pkg/image/registry_test.go

As part of https://github.com/oracle-cne/ock/pull/23, OCK gained the ability to leverage more container image transports for updates.  The CLI needs to be updated to allow those to be automatically configured.

Expand supported ostree tranports

---

pkg/cluster/driver/byo/byo.go
pkg/cluster/driver/none/none.go
pkg/cluster/update/update.go
pkg/constants/k8s_constants.go

There was a regression in [2.1.0](https://github.com/oracle-cne/ocne/pull/252) that prevents the cluster nodes from becoming ready.  When the kube-proxy application is installed, the address of the kube-apiserver is not actually set.  The result is that kube-proxy is unable to configure the service network that other pods (notably the CNI) require to communicate with kube-apiserver.  Net result: most pods cannot start.
The root cause of *that* is a failure to return a correct address for kube-apiserver from the byo and none providers.

Ensure that kube-apiserver IP is valid for byo and none providers

---

pkg/catalog/types.go
pkg/commands/catalog/mirror/mirror.go
pkg/constants/constants.go

Check the "ocne.oracle.com/mirror" annotation and don't add them to "ocne catalog mirror" if the annotation is "false".
```
$ ./out/linux_amd64/ocne catalog search --name embedded | grep kube-proxy
kube-proxy                 	2.0.0
$ ./out/linux_amd64/ocne catalog mirror | grep kube-proxy
$
```

Respect the mirror annotation from the catalog

---

pkg/commands/catalog/copy/copy.go

Added logic to retry image copying if a 500 error is encountered with a delay between each retry.

254-500-error-when-mirror-the-catalog

---

doc/cluster-management/upgrade.md

2.1.1 includes support for alternate ostree transports for updates.  An example would be nice.

Add example of alternate ostree configuration

---

pkg/cluster/template/olvm/ignition.go
pkg/cluster/template/templates/capi-olvm.yaml
pkg/k8s/node.go

Update the olvm CAPI client to work with new OCK image.  Cluster start was broken and is now fixed:
```
ocne cluster start --provider olvm  --cluster-name demo --config ~/.ocne/olvm-demo-cluster-config.yaml
INFO[2025-03-19T15:05:26-04:00] Installing cert-manager into cert-manager: ok 
INFO[2025-03-19T15:05:27-04:00] Installing core-capi into capi-system: ok 
INFO[2025-03-19T15:05:27-04:00] Installing olvm-capi into cluster-api-provider-olvm: ok 
INFO[2025-03-19T15:05:28-04:00] Installing bootstrap-capi into capi-kubeadm-bootstrap-system: ok 
INFO[2025-03-19T15:05:28-04:00] Installing control-plane-capi into capi-kubeadm-control-plane-system: ok 
INFO[2025-03-19T15:05:29-04:00] Waiting for Kubadm Control Plane Cluster API Controllers: ok 
INFO[2025-03-19T15:05:29-04:00] Waiting for Olvm …
```

update olvm template for new OCK image

---

cmd/image/upload/upload.go
pkg/commands/image/upload/upload.go

It's a hassle to always have to provide CLI arguments when uploading OCI images.  Usually the cluster config or defaults file have that information in them already.  It is now possible to consume these values straight out of the cluster config.
```
$ ocne image upload --version 1.29 --type oci --file ~/.ocne/images/boot.qcow2-1.29-amd64.oci --arch amd64
INFO[2025-03-20T16:49:14Z] Uploading image to object storage: ok 
INFO[2025-03-20T17:03:01Z] Importing compute image: [##########]: ok 
INFO[2025-03-20T17:03:01Z] Image OCID is ocid1.image.oc1.iad.aaaaaaaaaaaaaaaaaaaaa
$ ocne image upload --version 1.29 --type oci --file ~/.ocne/images/boot.qcow2-1.29-amd64.oci --arch amd64 --compartment afakecompartmenttoproveclioverrides
ERRO[2025-03-20T17:13:24Z] could not find compartment named …
```

Make image upload for oci images account for cluster config and defaults

---

buildrpm/ocne.spec
pkg/cluster/ignition/ignition.go
pkg/cluster/ignition/virtual_ip.go

The permissions on some configuration files for keepalived and nginx are too loose.  Tighten them up.  Since I was already in there, I made the default configuration files function from the get go as well.

Tighten up file permissions for virtual ip

---

pkg/commands/cluster/start/start.go

During the merging of main -> release/2.1 for release 2.1.2, the auto-merge appeared to succeed but actually introduced some breakage.  The gateway crd chart was being installed twice.  It's mostly cosmetic, as the same chart is re-installed immediately after the first install during cluster start, which is why it was missed during testing.

Correct mis-merge of main branch into release branch

---

buildrpm/ocne.spec
pkg/cluster/driver/capi/logScanner.go

When applying CAPI resources to a management cluster, not all resources are made in a timely fashion.  This can cause some transient failures in various controllers as the resource state shakes out.
For example
```
...
INFO[2025-04-02T18:59:46Z] Applying Cluster API resources               
ERRO[2025-04-02T18:59:46Z] Saw unexpected error message in OCI Cluster API provider logs: E0402 18:59:46.049435       1 ocicluster_controller.go:315] "Failed to get OCI cluster" err="OCICluster.infrastructure.cluster.x-k8s.io \"capi\" not found" 
INFO[2025-04-02T19:00:29Z] Waiting for kubeconfig: ok  
...
```
These should be tolerated.  Right now the list is limited to the one example that I have seen.  This check can be expanded as more examples are found.

Add error message toleration to oci provider logging

---

buildrpm/ocne.spec
pkg/cluster/driver/capi/capi.go
pkg/commands/cluster/start/start.go
pkg/k8s/kube-proxy.go

If your network connection is flaky, the CAPI controllers can take a while to put the kubelet-config ConfigMap into the cluster.  Best to wait for it for the sake of reliability.

Retry fetching kubelet-config during cluster start

---

doc/experimental/phase1/phase1.md

Update the instructions for upgrading ingress-nginx.  They did not take into account retaining a custom ConfigMap that Verrazzano created.

Update instructions for upgrading ingress-nginx

---

pkg/helm/helmcli.go
pkg/helm/helmcli_test.go

Fixed issue where new overrides were replacing existing ones.  The solution was to merge new overrides into existing ones.

Fix issue of ocne application update not properly reusing user supplied overrides

---

pkg/cluster/driver/olvm/apps.go
pkg/cluster/driver/olvm/start.go
pkg/config/config.go
pkg/config/types/types.go
pkg/constants/k8s_constants.go
pkg/util/nestedmap.go

Install ovirt-csi-driver during `cluster start --provider olvm`.   By default the driver is installed, and there is no config required.   The ovirt-csi-driver catalog chart value.yaml has the defaults.  
The following can be overridden.  
```  
olvm:
ovirtCsiDriver:
install: true (default)
caProvided: true
caConfigmapName: test-cm
controllerPluginName: test-controller
csiDriverName: test-csi-driver-2
namespace: test-csi-ns-2
nodePluginName: test-node
credsSecretName: test-secret
```
I installed ocne with standard olvm config, not ovirt-csi-driver overrides:
```
ocne cluster start --provider olvm --config ~/.ocne/olvm-demo.yaml 
INFO[2025-04-16T17:38:45-04:00] Installing cert-manager into cert-manager: ok 
INFO[2025-04-16T17:38:46-04:00] Installing core-capi into capi-system: ok …
```

Install ovirt-csi-driver during cluster start --provider olvm

---

pkg/cluster/template/olvm/ignition.go

Fix the OLVM ignition config code to correctly load the update.yaml.
Tested new OLVM CAP cluster and examined the update.yaml file
```
ocne cluster start --provider olvm --config ~/.ocne/olvm-demo.yaml 
INFO[2025-04-18T13:58:50-04:00] Installing cert-manager into cert-manager: ok 
INFO[2025-04-18T13:58:50-04:00] Installing core-capi into capi-system: ok 
INFO[2025-04-18T13:58:51-04:00] Installing olvm-capi into cluster-api-provider-olvm: ok 
INFO[2025-04-18T13:58:51-04:00] Installing bootstrap-capi into capi-kubeadm-bootstrap-system: ok 
INFO[2025-04-18T13:58:52-04:00] Installing control-plane-capi into capi-kubeadm-control-plane-system: ok 
INFO[2025-04-18T13:58:52-04:00] Waiting for Core Cluster API Controllers: ok 
INFO[2025-04-18T13:58:52-04:00] Waiting for Kubadm Boostrap Cluster API …
```

Fix update.yaml contents

---

pkg/constants/k8s_constants.go

The OLVM controller was failing to come up because we had recently changed the name.  Use the new name.

Update OLVM deployment name

---

pkg/commands/cluster/console/console.go
pkg/commands/cluster/join/join.go
pkg/k8s/pod.go

Accounts for cluster node names that have dots in them when admin pods need to be deleted.
```
$ ./out/linux_amd64/ocne cluster start -C mycluster.mydomain
INFO[2025-04-24T20:27:36Z] Creating new Kubernetes cluster with version 1.31 named mycluster.mydomain 
INFO[2025-04-24T20:28:28Z] Waiting for the Kubernetes cluster to be ready: ok 
INFO[2025-04-24T20:28:29Z] Installing core-dns into kube-system: ok 
INFO[2025-04-24T20:28:29Z] Installing kube-proxy into kube-system: ok 
...
$ kubectl get node
NAME                                 STATUS   ROLES           AGE   VERSION
mycluster.mydomain-control-plane-1   Ready    control-plane   49s   v1.31.6+2.el8
$ ./out/linux_amd64/ocne cluster console --node mycluster.mydomain-control-plane-1
sh-4.4# exit
$ kubectl get pods -A
NAMESPACE      NAME …
```

Ensure that admin pods are deleted when a node has a dot in the name

---

Makefile

The build fails if the developer build is enabled and the branch is empty.

Disable developer builds by default

---

pkg/cluster/driver/olvm/start.go
pkg/cluster/template/olvm/capi-olvm.go
pkg/util/olvmutil/olvm_resources.go

Fix bug where default secret was not being set correctly in the ocne client generated CAPI manifests. 
I created a cluster with the default secret as a test.
```
ocne cluster start  --provider olvm -c ~/.ocne/olvm-paul.yaml 
INFO[2025-05-02T14:35:39-04:00] Installing cert-manager into cert-manager: ok 
INFO[2025-05-02T14:35:40-04:00] Installing core-capi into capi-system: ok 
INFO[2025-05-02T14:35:40-04:00] Installing olvm-capi into cluster-api-provider-olvm: ok 
INFO[2025-05-02T14:35:41-04:00] Installing bootstrap-capi into capi-kubeadm-bootstrap-system: ok 
INFO[2025-05-02T14:35:41-04:00] Installing control-plane-capi into capi-kubeadm-control-plane-system: ok 
INFO[2025-05-02T14:35:42-04:00] Waiting for Core Cluster API Controllers: ok 
INFO[2025-05-02T14:35:42-04:00] Waiting for …
```

Fix bug where default secret was not being set correctly.

---

doc/manpages/ocne-config.yaml.md
doc/manpages/ocne-defaults.yaml.md
pkg/cluster/template/templates/capi-oci.yaml
pkg/config/config.go
pkg/config/types/types.go
pkg/constants/constants.go

The default disk size of 50Gb is not sufficient for any real workloads.  Asking users to create and edit a template for such a small change is silly.  Expose a configuration option directly.

Add boot volume size to the OCI provider config

---

doc/manpages/ocne-config.yaml.md
doc/manpages/ocne-defaults.yaml.md
pkg/cluster/driver/libvirt/libvirt.go
pkg/cluster/driver/libvirt/templates.go
pkg/config/config.go
pkg/config/types/types.go
pkg/constants/constants.go

Change the subnet for the slirp interface to something obscure, avoiding collisions with common subnets.  Also, make it configurable just in case.  192.18.255.0/24 was chosen because it is at the end of the range of a strange subnet.  See https://en.wikipedia.org/wiki/Reserved_IP_addresses

Pick an obscure slirp subnet

---

pkg/cluster/template/templates/capi-olvm.yaml
pkg/config/types/types.go

Update CLI OLVM provider to use new IPV6 config changes.
1. Add AutoConf
2. Remove IPV6 Subnet field
**Tested cluster start with both IPV6 and IPV4**
```
ocne cluster start  --provider olvm -c ~/.ocne/olvm-gz.yaml
INFO[2025-05-12T17:54:11-04:00] Installing cert-manager into cert-manager: ok 
INFO[2025-05-12T17:54:12-04:00] Installing core-capi into capi-system: ok 
INFO[2025-05-12T17:54:12-04:00] Installing olvm-capi into cluster-api-provider-olvm: ok 
INFO[2025-05-12T17:54:13-04:00] Installing bootstrap-capi into capi-kubeadm-bootstrap-system: ok 
INFO[2025-05-12T17:54:13-04:00] Installing control-plane-capi into capi-kubeadm-control-plane-system: ok 
INFO[2025-05-12T17:54:14-04:00] Waiting for Core Cluster API Controllers: ok 
INFO[2025-05-12T17:54:14-04:00] Waiting for Kubadm Boostrap …
```

Update CLI OLVM provider to use new IPV6 config changes

---

pkg/cluster/driver/none/none.go
pkg/commands/cluster/join/join.go
pkg/commands/cluster/join/scripts.go
pkg/k8s/tokens.go

A demo:
```
$ cat start.sh 
#! /bin/bash
#
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
source "$SCRIPT_DIR/env.sh"
set -x
PUBKEY="$(cat ~/.ssh/id_rsa.pub)"
create_node() {
NAME="$1"
create_domain "$NAME" "${NAME}.ign"
}
join_node() {
NAME="$1"
IP=$($SCRIPT_DIR/get-domain-ip.sh "${NAME}")
ssh -o StrictHostKeyChecking=no sshuser@$IP sudo cat /etc/kubernetes/admin.conf > kubeconfig.node
ocne cluster join -k kubeconfig.node --node "${NAME}" --destination "$KUBECONFIG" --log-level debug
}
create_node "${CLUSTER_NAME}-control-plane-1"
create_node "${CLUSTER_NAME}-control-plane-2"
create_node "${CLUSTER_NAME}-control-plane-3"
create_node "${CLUSTER_NAME}-worker-1"
create_node "${CLUSTER_NAME}-worker-2"
create_node "${CLUSTER_NAME}-worker-3"
sleep 120 …
```

Fix various issues with cluster join

---

README.md

Fixes below errors
```
sudo yum-builddep buildrpm/ocne.spec
....
....
No matching package to install: 'device-mapper-devel'
No matching package to install: 'gpgme-devel'
No matching package to install: 'helm >= 3.13.0'
No matching package to install: 'libassuan-devel'
No matching package to install: 'yq'
```
Note:  `ol9_ocne` does not have the necessary dependencies like yq, helm etc for Oracle Linux 9 at the moment. So I am not including it in the PR.

Added missing repos when building cli for Oracle Linux 8

---

pkg/cluster/template/olvm/ignition.go

Use an existing drop-in to disable ignition after first boot.  This is needed until the disable-ignition service is fixed, currently it is not enabled.  See https://github.com/oracle-cne/ock/issues/41
I tested by provisioning a 2 node cluster then rebooting the control plane node, then the worker node.  Both reboots hang without this fix.
Before the reboot you can see that the ignition.firstboot param is gone
```
rpm-ostree kargs
rw ip=dhcp rd.neednet=1 ignition.platform.id=openstack systemd.firstboot=off crashkernel=auto console=tty0 root=UUID=8b5a,,,d1 rd.timeout=120 ostree=/ostree/boot.1/ock/22687...f935/0
```
Before this, the kargs looked like this ( notice ignition.firstboot=1 )
```
rpm-ostree kargs
rw ip=dhcp rd.neednet=1 ignition.platform.id=openstack ignition.firstboot=1 …
```

Disable ignition after first boot

---

cmd/catalog/search/search.go
pkg/catalog/types.go

Sample output
```
> ocne cat search --name embedded
APPLICATION                	VERSION            
bootstrap-capi             	1.9.4              
bootstrap-capi             	1.7.1              
cert-manager               	1.16.3             
cert-manager               	1.14.5             
cert-manager               	1.9.1              
cert-manager-webhook-oci   	1.1.0              
control-plane-capi         	1.9.4              
control-plane-capi         	1.7.1              
core-capi                  	1.9.4              
core-capi                  	1.7.1              
coredns                    	2.0.0              
csi-driver-nfs             	4.11.0             
dex                        	2.39.1             
externalip-webhook         	1.0.0              
flannel …
```

Identify deprecated charts in the ocne catalog search output

---

pkg/config/config.go
pkg/constants/k8s_constants.go

Add default network interface for olvm.
**Tested config with missing interface field for both CP and Worker**
```
virtualMachine:
memory: "16GB"
network:
interfaceType: virtio
...
```
**Created OLVM cluster**
```
ocne cluster start  --provider olvm -c ~/.ocne/olvm-paul.yaml
INFO[2025-05-29T13:40:49-04:00] Installing cert-manager into cert-manager: ok 
INFO[2025-05-29T13:40:50-04:00] Installing core-capi into capi-system: ok 
INFO[2025-05-29T13:40:50-04:00] Installing olvm-capi into cluster-api-provider-olvm: ok 
INFO[2025-05-29T13:40:51-04:00] Installing bootstrap-capi into capi-kubeadm-bootstrap-system: ok 
INFO[2025-05-29T13:40:51-04:00] Installing control-plane-capi into capi-kubeadm-control-plane-system: ok 
INFO[2025-05-29T13:40:52-04:00] Waiting for Core Cluster API Controllers: ok …
```

Add default network interface for olvm

---

pkg/cluster/ignition/ignition.go
pkg/cluster/ignition/library.go
pkg/cluster/ignition/virtual_ip.go
pkg/cluster/template/olvm/ignition.go
pkg/commands/cluster/dump/scripts.go
pkg/commands/cluster/join/scripts.go

Summary of changes:
- Changes to keepalived
- Changed /etc/ocne/keepalived-copy-kubeconfig.sh to copy the kubelet kubeconfig to /etc/keepalived, as well as the certificate files (if the kubeconfig does not embed the cert data)
- Changes to /etc/keepalived/check_apiserver.sh
- Use the kubelet kubeconfig instead of the admin kubeconfig
- Added checks for API Server and Nginx being up based on their processes being actively bound to ports
- Removed logic that managed changes to nginx.conf
- Changes to /etc/ocne/nginx.conf
- Added least_conn to nginx.conf
- Added fail_timeout=10s max_fails=1 to each server definition
- Added new service named ocne-nginx-refresh
- The logic that use to reside in the keepalived service for managing nginx.conf changes was moved to this new service
- The new …

Resolve issue of OLVM CAPI cluster node remaining in SchedulingDisabled state

---

pkg/cluster/template/olvm/capi-olvm.go
pkg/cluster/template/olvm/ignition.go

Set IPV6 default route on each Kubernetes node if IP V6 is being used.  This fixes problem where Flannel would not start because it could not find the IPV6 interface for the default route.
**Tested IPV6 dual stack**
```
ocne cluster start  --provider olvm -c ~/.ocne/olvm-paul-v6.yaml 
INFO[2025-06-16T16:47:14-04:00] Installing cert-manager into cert-manager: ok 
INFO[2025-06-16T16:47:15-04:00] Installing core-capi into capi-system: ok 
INFO[2025-06-16T16:47:15-04:00] Installing olvm-capi into cluster-api-provider-olvm: ok 
INFO[2025-06-16T16:47:16-04:00] Installing bootstrap-capi into capi-kubeadm-bootstrap-system: ok 
INFO[2025-06-16T16:47:16-04:00] Installing control-plane-capi into capi-kubeadm-control-plane-system: ok 
INFO[2025-06-16T16:47:17-04:00] Waiting for Core Cluster API …
```

Set IPV6 default route
