oracle-cne/ocne

- doc/experimental/oam-to-kubernetes.md
Add a new doc sub-folder named "experimental"
Initialize with content on OAM to Kubernetes mappings.
> Add experimental doc folder with initial content

- doc/experimental/disable-verrazzano.md
Experimental instructions for disabling Verrazzano.
> Instructions for disabling Verrazzano

- doc/experimental/README.md
- doc/experimental/introduction.md
- doc/experimental/phase1.md
- doc/experimental/phase2.md
- doc/experimental/phase3.md
Added a top level document for the experimental docs, and linked in some sub-level documents.
> Create experimental top level document for migration

- doc/experimental/phase1.md
- doc/experimental/upgrade-istio.md
Update the experimental doc per the linked issue.
Moved Istio upgrade instructions into a separate document.
> Update experimental instructions to work for Verrazzano 1.6.12

- doc/experimental/ock-upgrade.md
- doc/experimental/phase1.md
- doc/experimental/phase2.md
- doc/experimental/phase3.md
Add verrazzano module operator removal instructions and a few other cleanup items.
Break up instructions to update single ock node.
> Add verrazzano module operator removal instructions and minor restructuring

- doc/experimental/phase2.md
Fix minor typos in module operator scale-in instructions
> Fix minor typos in module operator scale-in instructions

- doc/experimental/phase1/phase1.md
Add instructions to patch verrazzano-authproxy to use ingress-nginx 1.9.6
> Add instructions to patch verrazzano-authproxy to use ingress-nginx 1.9.6

- doc/experimental/README.md
- doc/experimental/phase1/kube-prometheus-stack.md
Change kube-prometheus-stack migration for a single replica.  There are notes on what to do if you have more than one replica.
> Change kube-prometheus-stack migration for a single replica

- doc/experimental/phase1/phase1.md
Document how to delete Verrazzano CR
> Document how to delete Verrazzano CR

- doc/experimental/phase1/phase1.md
Change WebLogic migration instructions to use Helm only.
> WebLogic migration using Helm only

- doc/experimental/README.md
- doc/experimental/introduction.md
- doc/experimental/phase1/phase1.md
- doc/experimental/phase2/phase2.md
- doc/experimental/phase3/phase3.md
Add next page links to migration top-level docs
> Add next page links to migration docs

- doc/experimental/introduction.md
Cleanup of migration introduction
> Cleanup of migration introduction

- doc/experimental/introduction.md
- doc/experimental/phase1/kube-prometheus-stack.md
- doc/experimental/phase1/oam-remove-objects.md
- doc/experimental/phase1/phase1.md
- doc/experimental/phase1/upgrade-istio.md
This is response to doing the full migration testing of phase 1 from start to finish.
1. Fix AuthorizationPolicies that had the wrong service account
2. Create separate section for workload restart in the Istio migration
3. Instructions to restart apps to pick up proxyv2
4. Confirm OAM objects are deleted
5. Misc cleanup
> Migration doc cleanup plus fix AuthorizationPolicy configuration

- pkg/commands/cluster/start/start.go
- pkg/constants/k8s_constants.go
Fix the override of the image for the init-container in the UI deployment.
> Fix override of ui init container

- pkg/helm/helmcli.go
In this PR, I fixed an issue where the namespace was not being passed in correctly to the Helm Configuration. I edited the once-catalog chart to remove the namespace from the chart and verified that when the `application install` command was run on this chart with a namespace specified, the chart was installed in that namespace. I also verified that these changes don't seem to impact existing Helm behavior/functionality in the CLI. 
Successful installation of chart with namespace specified:
```
./ocne application install -c embedded -n ocne-system -N ocne-catalog
INFO[2024-10-28T10:34:35-04:00] Application installed successfully    
```
Verification of Chart being installed in the correct namespace: 
```
./ocne application list -n ocne-system
Releases
NAME            NAMESPACE       CHART …
```
> Fix Helm Application Installation Issues

- pkg/constants/k8s_constants.go
Fix typo in CatalogServiceName constant to resolve bug reported in linked issue.
> Fix typo in CatalogServiceName constant

- go.mod
- pkg/k8s/kubectl/copy.go
Remove direct dependency on github.com/pkg/errors.
> Remove direct dependency on github.com/pkg/errors

- doc/cluster-management/byo.md
- doc/cluster-management/oci.md
Fixes broken links in all documentation including byo pages.
> 142 broken links in byo documentation

- THIRD_PARTY_LICENSES.txt
- go.mod
- pkg/k8s/apply.go
Made changes per the associated issue.
> Revert changes to remove apply.go

- doc/experimental/phase1/phase1.md
- doc/experimental/phase2/phase2.md
In this PR, I add instructions for etcd backup and module deletion.
> Add instructions for etcd backup and module deletion

- cmd/application/install/install.go
- cmd/application/template/template.go
- cmd/application/update/update.go
- cmd/catalog/search/search.go
- doc/application-management/application-management.md
- pkg/constants/k8s_constants.go
See associated task for description.
> Document the usage of the embedded catalog

- doc/application-management/application-management.md
- pkg/commands/catalog/ls/ls.go
```
$ ocne catalog list
CATALOG                                            	NAMESPACE  	PROTOCOL	URI
Oracle Cloud Native Environment Application Catalog	ocne-system	helm    	   
embedded                                           	           	helm    	   
```
> Add the embedded catalog to the output of ocne catalog list

- doc/cluster-management/olvm.md
Add more OLVM documentation for fields that were missed by the initial commit.
> add more OLVM doc field descriptions

- doc/manpages/ocne-config.yaml.md
- doc/manpages/ocne-defaults.yaml.md
Added a explanation for the password field available in cluster config and defaults yaml. Added further explanation regarding how to generate and use the password.
> Added explanation for password

- doc/experimental/phase1/oam-to-kubernetes.md
- doc/experimental/phase1/oauth2-proxy.md
- doc/experimental/phase1/phase1.md
Document migration from verrazano oauth proxy to oauth2 proxy.
> Document migration from verrazano oauth proxy to oauth2 proxy

- doc/cluster-management/byo.md
- doc/cluster-management/cluster-management.md
- doc/end-to-end/end-to-end.md
- doc/end-to-end/ock.md
- doc/table-of-contents.md
This example has a completely customized byo install from ock-forge all the way to cluster node.
> Add ock-forge -> byo example

- doc/experimental/phase1/oauth2-proxy.md
Minor updates to the doc, mostly spelling and formatting.
> 267 minor updates to the oauth2 proxy migration doc

- doc/experimental/phase1/phase1.md
- doc/experimental/phase1/upgrade-keycloak.md
Add upgrade of Keycloak to the experimental docs
> Add upgrade of Keycloak to the experimental docs

- pkg/application/pods.go
- pkg/application/replication.go
- pkg/cluster/driver/capi/capi.go
- pkg/cluster/driver/capi/logScanner.go
- pkg/k8s/client/client.go
- pkg/k8s/client/config.go
- pkg/k8s/daemonset.go
- pkg/k8s/deployment.go
- pkg/k8s/pod.go
- pkg/k8s/replicaset.go
- pkg/k8s/selectors.go
- pkg/util/logutils/read.go
- pkg/util/parser.go
It's a pain to figure out what is going on when OCI CAPI gets wedged.  Users have to figure out what pods are in charge of various process and where to find various errors.  It's better to figure that out on the fly, as all that information is known to the CLI.
Here's an example
```
[opc@ol9 ocne]$ ./out/linux_amd64/ocne cluster start -c ~/tools/capi-v8odev.yaml 
INFO[2025-03-17T15:05:47Z] Installing cert-manager into cert-manager: ok 
INFO[2025-03-17T15:05:48Z] Installing core-capi into capi-system: ok 
INFO[2025-03-17T15:05:48Z] Installing capoci into cluster-api-provider-oci-system: ok 
INFO[2025-03-17T15:05:49Z] Installing bootstrap-capi into capi-kubeadm-bootstrap-system: ok 
INFO[2025-03-17T15:05:49Z] Installing control-plane-capi into capi-kubeadm-control-plane-system: ok …
```
> Add log analysis to oci provider to print errors

- doc/cluster-management/olvm.md
- pkg/cluster/template/olvm/ignition.go
minor OLVM doc changes and copyright updates.
> minor OLVM doc changes and copyright

- pkg/cluster/driver/capi/capi.go
Fix segment violation when uploading an image for the OCI provider.
> Add initialization of cluster config to upload request

- buildrpm/ocne.spec
> Release 2.1.2

- doc/experimental/phase1/phase1.md
Simplify ingress-nginx upgrade instructions
> Simplify ingress-nginx upgrade instructions

- doc/cluster-management/olvm.md
> minor OLVM doc changes

- doc/cluster-management/upgrade.md
- main.go
- pkg/cluster/driver/capi-common/capi.go
- pkg/cluster/driver/capi/capi.go
- pkg/cluster/driver/oci/capi.go
- pkg/cluster/driver/oci/driver.go
- pkg/cluster/driver/oci/logScanner.go
- pkg/cluster/driver/oci/stage.go
- pkg/cluster/driver/olvm/stage.go
In addition to documentation updates, refactor some package names.
> Documentation updates for OLVM cluster upgrade

- pkg/cluster/template/olvm/ignition.go
Enable ocne-image-cleanup.service for OLVM
> Enable ocne-image-cleanup.service for OLVM

- main.go
- pkg/features/features.go
> remove feature flag for OLVM

- pkg/cluster/driver/olvm/apps.go
- pkg/cluster/driver/olvm/start.go
- pkg/commands/image/upload/upload_olvm.go
- pkg/config/types/types.go
- pkg/ovirt/ovclient/ovclient.go
- pkg/ovirt/rest/http/httpclient.go
Add support for insecureSkipTLSVerify for the OLVM CAPI provider
> Add support for insecureSkipTLSVerify for the OLVM CAPI provider

- doc/cluster-management/olvm.md
Update the OLVM doc to use new configuration that works with the OLVM CAPI CRD changes.
> Update the OLVM doc with new configuration

- doc/experimental/phase1/migrate-calico.md
> Migrate default calico install 1.x to be helm manageable
